services:
  mySQL:
    image: mysql:latest
    hostname: mySQL
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "123456789"
      MYSQL_DATABASE: "scraper"
    networks:
      - scraper
    depends_on:
      - torproxy

  crawler:
    image: crawler:latest
    networks:
      - scraper
    depends_on:
      - mySQL

  torproxy:
    image: dperson/torproxy:latest
    networks:
      - scraper

  server:
    image: server:latest
    networks:
      - scraper
      - default
    depends_on:
      - mySQL
    ports:
      - "3000:80"

networks:
  scraper:
    driver: bridge
