services:
  mySQL:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "123456789"
      MYSQL_DATABASE: "scraper"
    hostname: mySQL
    networks:
      - scraper
    volumes:
      - mysqlvolume:/home/node/app

  crawler:
    image: crawler:latest
    restart: always
    networks:
      - scraper

  analyzer:
    image: analyzer:latest
    # restart: always
    networks:
      - scraper

  torproxy:
    image: dperson/torproxy:latest
    networks:
      - scraper

  server:
    image: server:latest
    networks:
      - scraper
    ports:
      - "3000:80"
    restart: always

  client:
    image: client:latest
    networks:
      - scraper
      - default
    depends_on:
      - server
    ports:
      - "8080:80"

networks:
  scraper:
    driver: bridge

volumes:
  mysqlvolume:
